# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/react"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/vue"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/vue2"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/vue2/docs" # vue2 docs app
    ignore:
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "monthly"      
  - package-ecosystem: "npm"
    directory: "/svelte"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "monthly"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'      
